name: Multi-Container Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K[0-9.]+')" \
          -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies with Pipenv
      run: pipenv install 

    - name: Build and start services with Docker Compose
      run: |
        docker-compose -f docker_compose.yml up
      working-directory: ./

    - name: Run integration tests
      run: pipenv run pytest integration_test/test_integration.py

    - name: Tear down services
      if: always()
      run: docker-compose down
      working-directory: ./
